# Generated by Django 4.2.18 on 2025-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_comment',
            field=models.IntegerField(default='placeholder'),
            preserve_default=False,
        ),
    ]
