# Generated by Django 4.2.16 on 2024-11-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default=1, upload_to='authors/images/'),
            preserve_default=False,
        ),
    ]
