# Generated by Django 4.2.17 on 2025-01-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0009_book_published_countries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countrie',
            new_name='Country',
        ),
    ]
