# Generated by Django 4.2.19 on 2025-03-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
