# Generated by Django 4.2.18 on 2025-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formExercise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignOn',
        ),
        migrations.AlterField(
            model_name='form',
            name='sign_on',
            field=models.IntegerField(choices=[(1, 'Mail'), (2, 'Payroll'), (3, 'Self-service')], default=2),
        ),
    ]
