# Generated by Django 4.2.19 on 2025-03-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='year',
        ),
    ]
