# Generated by Django 4.2.19 on 2025-03-06 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_age_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(54)]),
            preserve_default=False,
        ),
    ]
